apiVersion: v1
kind: Secret
metadata:
  name: twittersecrets
type: Opaque
data:
  TWITTER_API_KEY: xoxoxo
  TWITTER_API_SECRET: blablabla==
  TWITTER_ACCESS_TOKEN: xoxoxoxo
  TWITTER_ACCESS_TOKEN_SECRET: xoxoxoxo==
  TWITTER_USERNAME: xoxoxoxo==
